version: '3'
services:
  app:
    restart: unless-stopped
    stdin_open: true
    tty: true
    image: node:20
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash
    user: node