version: '3'
services:
  app:
    restart: unless-stopped
    stdin_open: true
    tty: true
    image: node:20
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash
    user: node
    environment:
      - container=docker
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp-data:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:::upload